[project]
name = "speech-to-speech-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=2.45.0",
    "pillow>=12.3.0",
    "pygame>=2.6.0",
    "pyttsx3>=2.99",
    "sounddevice>=0.5.0",
    "websockets>=12.0",
]
